import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Reshape, Bidirectional, LSTM, Dense, Dropout, Layer
import tensorflow.keras.backend as K

# =====================================================================
# 1. DEFINE THE ATTENTION LAYER ARCHITECTURE
# =====================================================================
# Keras requires us to write custom layers by subclassing the baseline 'Layer' module.
# This Attention Mechanism learns which specific time frames carry the most emotional weight.

class AttentionLayer(Layer):
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # This function runs ONCE when the model is compiled.
        # It creates the mathematical weight matrix (W) that the layer uses to score frame importance.
        # input_shape[-1] represents the number of hidden features coming out of the BiLSTM.
        self.W = self.add_weight(name="att_weight", 
                                 shape=(input_shape[-1], 1),
                                 initializer="normal", 
                                 trainable=True)
        super(AttentionLayer, self).build(input_shape)

    def call(self, x):
        # This function runs during EVERY training step. It computes attention scores.
        # 1. Multiply the BiLSTM outputs (x) by our learned weight matrix (W) to get raw scores.
        et = K.dot(x, self.W)
        et = K.squeeze(et, axis=-1) # Remove extra dimensions to make it a flat timeline score
        
        # 2. Pass scores through a Softmax function. This scales time-frame importance from 0 to 1.
        # The sum of importance scores across all 130 frames will equal exactly 1.0.
        at = K.softmax(et)
        at = K.expand_dims(at, axis=-1) # Expand dimensions back to multiply smoothly against features
        
        # 3. Multiply the original BiLSTM features by their calculated importance scores.
        # This mathematically amplifies emotional frames (e.g., screams) and silences useless noise.
        output = x * at
        
        # 4. Sum up all the frames along the time axis to compress the whole timeline into a 
        # single, comprehensive "Context Vector" for the Dense Layer.
        return K.sum(output, axis=1)

    def compute_output_shape(self, input_shape):
        # Informs Keras of the output shape: [Batch_Size, BiLSTM_Hidden_Features] (Time axis is gone)
        return (input_shape[0], input_shape[-1])


# =====================================================================
# 2. DATA LOADING AND COMPREHENSIVE FEATURE FUSION
# =====================================================================

print("Executing Data Loading Phase...")

# Load the fast binary arrays generated by your augmented preprocessing script
X_mfcc = np.load("X_mfcc.npy")      # Current Shape: (5760, 40, 130)
X_mel = np.load("X_mel.npy")        # Current Shape: (5760, 128, 130)
X_chroma = np.load("X_chroma.npy")  # Current Shape: (5760, 12, 130)
y = np.load("y.npy")                # Target numerical label array. Shape: (5760,)

# Concatenate (glue) all three feature arrays together along Axis 1 (the feature rows axis).
# This stacks 40 MFCC rows + 128 Mel rows + 12 Chroma rows on top of each other.
X_combined = np.concatenate((X_mfcc, X_mel, X_chroma), axis=1) 
# Resulting Shape: (5760, 180, 130)

# CNN layers require a 4D tensor input: [Samples, Height, Width, Channels].
# Since our spectrogram features are grayscale images, we explicitly add a 1-channel dimension at the end.
X_final = np.expand_dims(X_combined, axis=-1)
# Final Input Shape for Neural Network: (5760, 180, 130, 1)

print(f"Features fused successfully. Final Input Matrix Shape: {X_final.shape}")


# =====================================================================
# 3. SPLIT DATASET INTO TRAINING AND TESTING SETS
# =====================================================================
# To keep your DRDO evaluation strictly honest, we isolate 20% of the data completely.
# The model will train exclusively on 80% and validate its real-world performance on the remaining 20%.

X_train, X_test, y_train, y_test = train_test_split(
    X_final, 
    y, 
    test_size=0.2,          # 20% validation split (1,152 samples for testing, 4,608 for training)
    random_state=42,        # Standard seed to ensure your train/test shuffle splits identically every run
    stratify=y              # Critically ensures equal distribution of the 8 emotion classes in both sets
)


# =====================================================================
# 4. END-TO-END UNIFIED MODEL ASSEMBLY LINE (CNN + BiLSTM + Attention)
# =====================================================================

print("\nAssembling Neural Network Architecture Layers...")

model = Sequential()

# ---------------------------------------------------------------------
# DEPARTMENT 1: THE CNN PLUG (Spatial-Frequency Feature Extraction)
# ---------------------------------------------------------------------
# The CNN treats the audio map like an image, scanning local regions to identify visual textures.

# Conv2D Layer 1: Scans with 32 distinct filters of size 3x3 pixels. 
# 'relu' (Rectified Linear Unit) activation introduces non-linearity, ignoring useless negative values.
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(180, 130, 1)))
model.add(MaxPooling2D(pool_size=(2, 2))) # Downsamples image by 512, keeping only the strongest peak features

# Conv2D Layer 2: Deeper layer with 64 filters to combine simple lines into highly abstract sound shapes.
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# ---------------------------------------------------------------------
# DEPARTMENT 2: THE BRIDGE (Reshaping for Sequential Processing)
# ---------------------------------------------------------------------
# LSTMs cannot read 4D image structures. They expect a 3D sequential timeline: [Samples, Time_Steps, Features].
# We use Reshape to flatten the spatial height and channel dimensions directly into the time grid.
# The timeline coordinates must line up perfectly with your remaining frames.
model.add(Reshape(target_shape=(model.output_shape[2], model.output_shape[1] * model.output_shape[3])))

# ---------------------------------------------------------------------
# DEPARTMENT 3: THE BiLSTM LOOP (Chronological Timeline Context)
# ---------------------------------------------------------------------
# Processes the sequence of extracted CNN features forward and backward in time simultaneously.
# return_sequences=True is mandatory because our Attention Layer needs to evaluate *every single frame*.
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(Dropout(0.3)) # Randomly deactivates 30% of memory cells to prevent overfitting

# ---------------------------------------------------------------------
# DEPARTMENT 4: THE ATTENTION COMPONENT (Selective Focus)
# ---------------------------------------------------------------------
# Evaluates every frame outputted by the BiLSTM and condenses them based on emotional importance.
model.add(AttentionLayer())

# ---------------------------------------------------------------------
# DEPARTMENT 5: THE DENSE + SOFTMAX CLOSURE (The Jury and The Verdict)
# ---------------------------------------------------------------------
# Step 1: Fully connected intermediate layer to mix and weight the attention features.
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3)) # Final regularization layer

# Step 2: The Final Output Classification Layer. 
# Units must equal exactly 8 because you have exactly 8 identified emotion classes.
# Softmax scales output into 8 precise percentage values adding up to exactly 1.0 (100%).
model.add(Dense(8, activation='softmax'))


# =====================================================================
# 5. COMPILATION AND SYSTEM TRACE SUMMARY
# =====================================================================

# Compile the entire integrated workflow
model.compile(
    # 'sparse_categorical_crossentropy' is used because our labels are single integers (0 through 7)
    loss='sparse_categorical_crossentropy', 
    optimizer='adam',                        # Robust, adaptive learning rate optimization algorithm
    metrics=['accuracy']                     # Tracks classification correctness percentage during runtime
)

# Print an architectural map showing input/output dimensions changing across every layer boundary
model.summary()


# =====================================================================
# 6. MODEL EXECUTION LOOP (Training Engine)
# =====================================================================

print("\nCommencing Model Optimization Training Loop...")

# Execute the training loop process
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test), # Check performance against unseen testing sets at every turn
    epochs=30,                        # The data will pass forward and backward through the loop 30 complete times
    batch_size=32                     # Processes audio clips in groups of 32 before modifying internal weights
)

print("\nModel Architecture fully optimized and trained.")

# Save the final trained weights configuration file
model.save("ser_cnn_bilstm_attention_model.h5")
print("Trained model architecture successfully exported to disk as 'ser_cnn_bilstm_attention_model.h5'")